services:
  proxy:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    expose:
      - 3000

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    expose:
      - 4200
